services:
  frontend:
    container_name: frontend1
    build:
      context: ./frontend
      dockerfile: dockerfile

    ports:
      - "8081:8081"
      - "19000:19000"
      - "19001:19001"
      - "19002:19002"

    environment:
      - NODE_ENV=development
      - EXPO_DEVTOOLS_LISTEN_ADDRESS=0.0.0.0
      - REACT_NATIVE_PACKAGER_HOSTNAME=192.168.1.135

    volumes:
      - ./frontend:/app
      - /app/node_modules
    # command: npm start --lan --clear
    # command: npx expo start --clear --lan
    # command: npx expo start --clear --tunnel
    stdin_open: true
    tty: true

  # Add backend service below when ready
  backend:
    container_name: backend1
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"

    volumes:
      - ./backend:/app
    
    depends_on:
      - db
      - frontend
    env_file:
      - .env

  db:
    # we can not use pg vector if we dont wnat since we are not leveraging it
    image: ankane/pgvector
    container_name: items_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:

# docker-compose exec -it myfrontend /bin/bash