services:
  frontend:
    build:
      context: ./frontend
      dockerfile: dockerfile
    ports:
      - "8081:8081"
    environment:
      - NODE_ENV=development
      - EXPO_DEVTOOLS_LISTEN_ADDRESS=0.0.0.0
    volumes:
      - ./frontend:/app
      # - /app/node_modules
    command: npx expo start --tunnel --clear
    # command: npx expo start --clear --lan
    stdin_open: true
    tty: true

  # Add backend service below when ready
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"

    volumes:
      - ./backend:/app
    
    depends_on:
      - db
      - frontend
    env_file:
      - .env

  db:
    # we can not use pg vector if we dont wnat since we are not leveraging it
    image: ankane/pgvector
    container_name: studyguider_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: