# Use official Python image
FROM python:3.12-slim


RUN apt-get update && apt-get install -y \
    libpq-dev gcc \
    && rm -rf /var/lib/apt/lists/*

# Set working directory inside container
WORKDIR /app

# Copy project files into container
COPY . .

# Install dependencies (if you have requirements.txt)
RUN pip install --no-cache-dir -r requirements.txt

RUN pip install httpx

EXPOSE 8000

# RUN mkdir -p /app/data


# docker run -it --user root tempbackend /bin/bash

# Default command to run your app
RUN chmod +x /app/entrypoint.sh


CMD ["sh","/app/entrypoint.sh"]